[build]
  publish = "dist"
  command = "yarn generate"

# https://github.com/bahmutov/netlify-plugin-github-dispatch
[[plugins]]
  package = "netlify-plugin-github-dispatch"
  [plugins.inputs]
    owner = "bennymeade" # use the target organization name
    repo = "netlify-site-with-cypress-tests" # use the target repo name
    workflow = ".github/workflows/e2e.yml" # use workflow relative path
